### ISSUE TITLE
Extreme Cost value breaks task assign

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#17]
I gave a extreme cost value to see what happens.
![image](https://github.com/ozmen54/tasker/assets/93757827/d8083d36-397c-49b4-897c-015c574374e6)
And it translated it to scientific notation here.
![image](https://github.com/ozmen54/tasker/assets/93757827/0a5a82bf-3d12-447f-8257-ab4cd8e7dffd)
after i select the level of alper (which is level 2) hit assign button and get this error.
![image](https://github.com/ozmen54/tasker/assets/93757827/c5ed563d-5e6a-4aca-b312-0aaa35884865)
It added the task just visually on alper’s calendar. And Every time i refresh at this page it continued to add tasks visually, stacks them next to each other.
![image](https://github.com/ozmen54/tasker/assets/93757827/dc3e1f22-38ca-4986-9825-d052800a5bf3)

**Comment by ozmen54** [comment]
Fixed. Thanks!
