### ISSUE TITLE
Values gets deleted in task assign panel

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#19]
It doesn’t save some of the states of the task wants to be assigned. (date and tasker)
![image](https://github.com/ozmen54/tasker/assets/93757827/c3cf67e0-7642-43f5-9664-deaad11ec006)
![image](https://github.com/ozmen54/tasker/assets/93757827/3f44184f-22b0-4430-b0f7-8a311f69ce93)

**Comment by ozmen54** [comment]
This is correct behavior. Any changes above search require a new search for the tasker. If you modify inputs, then old selection gets assigned to then result might not be a proper selection.
