### ISSUE TITLE
Exceeding the available time interval

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#2]
If i give a job that exceeds the tasker's available time interval, it accepts and puts all the job to the calendar. And the available time doesn't get replaced by assigned task.

**Preparing the task:**
![Untitled](https://github.com/ozmen54/tasker/assets/93757827/b627bdfa-cd89-444a-a325-5c4717f0ab63)
**After giving the task:**
![image](https://github.com/ozmen54/tasker/assets/93757827/88320a74-0477-4886-ad95-f223045da388)
![image](https://github.com/ozmen54/tasker/assets/93757827/85ddb6e5-a38e-438d-a09a-30e44abbad7f)

**Comment by ozmen54** [comment]
Estimated time hours enterance is limitted max. 8 hour at front end. 
This can be defined as a global conf parameter later. Currently this bug is fixed, and issue is closed.
