### ISSUE TITLE
Level indication at tasker selection screen

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#21]
If we indicate the tasker level at tasker selection, it would be more convenient.
![image](https://github.com/ozmen54/tasker/assets/93757827/743355c4-9a6e-427a-9074-884f5a3c60e9)

**Comment by ozmen54** [comment]
Good idea, done. Tasker image is aldo added. The Id column is removed. It was just for debugging, and forgotten. Id is not a user interest.
