### ISSUE TITLE
Completed task can be expanded,shrinked and stacked

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#26]
There are two completed tasks:

![image](https://github.com/ozmen54/tasker/assets/93757827/d6239737-6b35-496b-b2b7-a244e7bebee4)

I try to expand the completed task:

![image](https://github.com/ozmen54/tasker/assets/93757827/6a5b4788-95ac-4858-b069-f92a6b1ebf45)

Turns out they stacked on top of each other:

![image](https://github.com/ozmen54/tasker/assets/93757827/95d39b52-d2f9-47b2-8f49-9b0bde4a2741)

This can be done too.

![image](https://github.com/ozmen54/tasker/assets/93757827/3c4f4286-6804-4c82-aaea-e99c98e15541)

**Comment by ozmen54** [comment]
Fixed.
