### ISSUE TITLE
Putting that day’s date as default on task assign panel

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#27]
It would be convenient to start assigning the task loaded that day's date like in this screenshot:

![image](https://github.com/ozmen54/tasker/assets/93757827/49cfc44d-8be7-42ff-b1f4-e4f66f51e961)

**Comment by ozmen54** [comment]
Done. Thanks.

**Comment by eskhas** [comment]
The page still comes without default date loaded automatically.

![image](https://github.com/ozmen54/tasker/assets/93757827/44dcc590-8d4d-47b8-ac9d-1fe7b36665d3)

**Comment by ozmen54** [comment]
Forgot to update running application. Now, it should be corrected.
