### ISSUE TITLE
Making calendar hours look like in AM,PM format

### ISSUE THREAD

**Issue by eskhas** [ozmen54/tasker#28]
We assign our task in am,pm format but in calendar it is 24 hours format. It would be convenient if calendar's hour appear as am,pm format.

![image](https://github.com/ozmen54/tasker/assets/93757827/a379ec9c-b961-426e-836f-6bdf91bb347f)

**Comment by ozmen54** [comment]
Since date-time comes from html, its format comes from local computer settings. Maybe in the future we should replace date-time picker that works with JavaScript. For now, it had better to postpone this improvement.
